### ISSUE TITLE
'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by konradre** [2kpr/ComfyUI-UltraPixel#1]
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI\custom_nodes\ComfyUI-UltraPixel\nodes.py", line 136, in ultrapixel
    image = model.process()
  File "D:\ComfyUI\custom_nodes\ComfyUI-UltraPixel\ultrapixel.py", line 81, in process
    models_b = core_b.setup_models(extras_b, skip_clip=True)
  File "D:\ComfyUI\custom_nodes\ComfyUI-UltraPixel\train\train_b.py", line 272, in setup_models
    ).items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by bbecausereasonss** [comment]
Same error, ultrapixel did not download any models into that folder; maybe into a cache folder?

**Comment by konradre** [comment]
> stage_b_lite_bf16.safetensor

Yeah this turned out to be it, thanks. I didnt have it elsewhere on my pc though. Found the place to get it manually:

https://huggingface.co/stabilityai/stable-cascade/tree/main

**Comment by bbecausereasonss** [comment]
Weird, I just put all the models into the custom node model folder and same error.

**Comment by 2kpr** [comment]
> I had this error and it was due to not having one of the Cascade model file in the Comfy folder ComfyUI/Models/Ultrapixel.
> 
> Check that folder and confirm you have the 6 safetensors files listed on the screenshot. If you do then I guess it's something else, but in my case I was missing the stage_b_lite_bf16.safetensor file in that folder. I found that file elsewhere on my HD, put a copy in the models/ultrapixel folder, and everything worked fine thereafter.
> 

Seems a lone space got accidently included in nodes.py, should be fixed now, sorry about that all!

["stage_b_lite_bf16.safetensors ", "stabilityai/stable-cascade"],
vs
["stage_b_lite_bf16.safetensors", "stabilityai/stable-cascade"],

Fixed in https://github.com/2kpr/ComfyUI-UltraPixel/commit/45d32bbe3777f1773dc0f74deea075d77b6d9278

**Comment by 2kpr** [comment]
> Same error, ultrapixel did not download any models into that folder; maybe into a cache folder?

It should download the files when you first run the workflow and place the files in a ComfyUI/models/ultrapixel dir, and make sure to update per the stage_b_lite_bf16 fix above.
