### ISSUE TITLE
执行队列报错如何解决

### ISSUE THREAD

**Issue by q875170573** [2kpr/ComfyUI-UltraPixel#33]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-UltraPixel\nodes.py", line 209, in ultrapixel
    image, edge_preview = model.process()
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-UltraPixel\ultrapixel.py", line 127, in process
    models = core.setup_models(extras)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-UltraPixel\train\train_t2i.py", line 420, in setup_models
    CLIPTextModelWithProjection.from_pretrained(
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\modeling_utils.py", line 3616, in from_pretrained
    if not has_file(pretrained_model_name_or_path, safe_weights_name, **has_file_kwargs):
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\utils\hub.py", line 655, in has_file
    response = get_session().head(
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 624, in head
    return self.request("HEAD", url, **kwargs)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\ComfyUI-aki-v1.3\python\lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/resolve/main/model.safetensors.index.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D614189C90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 84409660-003d-4ec1-bd56-dbb0c1002ee3)')

**Comment by q875170573** [comment]
已经下载了CLIP-ViT-bigG-14-laion2B-39B-b160k所有文件，但是不知道需要放在哪个目录才能生效？
