### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alex13by** [2kpr/ComfyUI-UltraPixel#8]
Installation dependency error, so the last two rely on manually cloned to the local installation, startup comfyui error

Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\nodes.py", line 4, in <module>
    from . import ultrapixel as up
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\ultrapixel.py", line 8, in <module>
    from .train import WurstCoreB
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\train\__init__.py", line 1, in <module>
    from .train_b import WurstCore as WurstCoreB
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\train\train_b.py", line 22, in <module>
    from ..modules.effnet import EfficientNetEncoder
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\modules\__init__.py", line 5, in <module>
    from .controlnet import ControlNet, ControlNetDeliverer
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\modules\controlnet.py", line 7, in <module>
    from ..core.utils import load_or_fail
  File "D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel\core\__init__.py", line 5, in <module>
    import wandb
ModuleNotFoundError: import of wandb halted; None in sys.modules

Cannot import D:\AI\ComfyUI-aki-v1\custom_nodes\ComfyUI-UltraPixel module for custom nodes: import of wandb halted; None in sys.modules

**Comment by 2kpr** [comment]
You ran pip install -r requirements.txt after cloning the repo?

**Comment by 2kpr** [comment]
See here: https://github.com/2kpr/ComfyUI-UltraPixel/issues/12#issuecomment-2235490598
